camdram/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'issues/', include('issues.urls', namespace='issues', app_name='issues')),
    url(r'', include('drama.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
            

drama/urls.py
import dal as dal
from django.contrib import auth
from django.conf.urls import patterns, url, include
from django.views.generic import TemplateView, ListView
from drama import viewsets, feeds, views
from rest_framework.routers import DefaultRouter
from registration.backends.default.views import ActivationView

router = viewsets.DramaRouter(trailing_slash=False)
router.register(r'roles', viewsets.RoleViewSet)
router.register(r'people', viewsets.PersonViewSet)
router.register(r'societies', viewsets.SocietyViewSet)
router.register(r'venues', viewsets.VenueViewSet)
router.register(r'shows', viewsets.ShowViewSet)
router.register(r'mailinglists', viewsets.EmailListViewSet)


vacancy_patterns = [
    url(r'^technical/$', views.techieads, name='technical'),
    url(r'^technical/feed/$', feeds.TechieAdFeed(), name='techiead_feed'),
    url(r'^auditions/$', views.auditions, name='auditions'),
    url(r'^auditions/diary/$', views.auditions_diary, name='auditions_diary'),
    url(r'^auditions/feed/$', feeds.AuditionFeed(), name='auditions_feed'),
    url(r'^applications/$', views.applications, name='applications'),
    url(r'^applications/feed/$', feeds.ApplicationFeed(), name='applications_feed'),
    url(r'^technical/(?P<slug>[^/]*)/$', views.techiead_item, name='techiead-item'),
    url(r'^auditions/(?P<slug>[^/]*)/$', views.audition_item, name='audition-item'),
    url(r'^applications/(?P<slug>[^/]*)/$', views.application_item, name='application-item'),
    url(r'^(?P<show_slug>[^/]*)/(?P<role_slug>[^/]*)/$', views.ad_role, name='ad_role'),
]


simple_register_patterns = [
    url(r'^activate/complete/$', TemplateView.as_view(template_name='registration/activation_complete.html'), name='registration_activation_complete'),
    # Activation keys get matched by \w+ instead of the more specific
    # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
    # that way it can return a sensible "invalid key" message instead of a
    # confusing 404.
    url(r'^activate/(?P<activation_key>\w+)/$', ActivationView.as_view(), name='registration_activate'),
    url(r'^register/$', views.EmailRegistrationView.as_view(), name='registration_register'),
    url(r'^register/complete/$', TemplateView.as_view(template_name='registration/registration_complete.html'), name='registration_complete'),
    url(r'^register/closed/$', TemplateView.as_view(template_name='registration/registration_closed.html'), name='registration_disallowed'),
    url(r'', include('django.contrib.auth.urls')),
]


urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^', include(router.urls)),
    url(r'^auth/', include(simple_register_patterns)),
    url(r'^diary/$', views.diary, name='diary'),
    url(r'^diary_week$', views.diary_week, name='diary_week'),
    url(r'^diary/(?P<week>[-0-9]+)$', views.diary, name='diary'),
    url(r'^diary_jump$', views.diary_jump, name='diary_jump'),
    url(r'^search', include('drama.haystack_urls'), name='search'),
    url(r'^ical/', feeds.FullCal(), name='ical'),
    url(r'^about/$', TemplateView.as_view(template_name="drama/about.html"), name='about'),
    url(r'^development/$', views.development, name='development'),
    url(r'^contact-us/$', views.contact_us, name='contact-us'),
    url(r'^privacy/$', TemplateView.as_view(template_name="drama/privacy.html"), name='privacy'),
    url(r'^vacancies/', include(vacancy_patterns)),
    url(r'^show-admin/$', views.show_admin, name='show-admin'),
    url(r'^approvals/$', views.approval_queue, name='approvals'),
    url(r'^approvals/(?P<key>[0-9]*)/ignore$', views.approval_ignore, name='approval-ignore'),
    url(r'approvals/(?P<key>[0-9]*)/approve$', views.approval_approve, name='approval-approve'),
]

issues/urls.py
from django.conf.urls import patterns, url, include
from issues import views

urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^(?P<key>[0-9]*)$', views.detail, name='detail'),
    url(r'^(?P<key>[0-9]*)/close$', views.close, name='close'),
    url(r'^(?P<key>[0-9]*)/claim$', views.claim, name='claim'),
]

drama/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.http import HttpResponse, Http404
from django.core.urlresolvers import reverse
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from haystack.query import SearchQuerySet
from django.views.generic import TemplateView, DetailView, CreateView, UpdateView, DeleteView, ListView, View
from drama import util, models, forms
import json
import datetime
import dal
import hashlib
from registration.backends.default.views import RegistrationView
from guardian.shortcuts import assign_perm, get_objects_for_user, remove_perm, get_users_with_perms
from collections import namedtuple
from django.views.decorators.http import require_http_methods, require_POST
import reversion
from django.db import transaction
from django.template import defaultfilters

WeekContainer = namedtuple('WeekContainer', 'name label diary start_date current')

def index(request):
    today = timezone.now().date()
    start_date = datetime.date.fromordinal(today.toordinal() - today.weekday())
    end_date = datetime.date.fromordinal(today.toordinal() - today.weekday() + 6)
    performance_objects = models.Performance.objects.filter(end_date__gte=start_date, start_date__lte=end_date, show__approved=True).distinct()
    performances = 0
    for p in performance_objects:
        performances += p.performance_count(start_date, end_date)
    dates = [start_date + datetime.timedelta(weeks=x) for x in range(-4,11)]
    weeks = []
    for date in dates:
        current = False
        if date == start_date:
            current = True
            label = 'This week'
        elif date == start_date + datetime.timedelta(weeks=1):
            label = 'Next week'
        else:
            label = '{} - {}'.format(defaultfilters.date(date,'j b').title(), defaultfilters.date(date + datetime.timedelta(days=6),'j b').title())
        weeks.append(WeekContainer(name=models.TermDate.get_weeklabel(date),
                                   current = current,
                                   label=label,
                                   diary=util.diary_week(models.Performance.objects.approved(), date, hide=(not current)),
                                   start_date = date))
    context = {
        'shows': models.Show.objects.filter(performance__end_date__gte=start_date, performance__start_date__lte=end_date).filter(approved=True).distinct().count(),
        'venues': models.Venue.objects.filter(performance__end_date__gte=start_date, performance__start_date__lte=end_date).filter(performance__show__approved=True).distinct().count(),
        'people': models.Person.objects.filter(roleinstance__show__performance__end_date__gte=start_date, roleinstance__show__performance__start_date__lte=end_date, roleinstance__show__approved=True).distinct().count(),
        'performances': performances,
        'auditions': models.AuditionInstance.objects.filter(end_datetime__gte=timezone.now()).order_by('end_datetime', 'start_time').filter(audition__show__approved=True).select_related('audition')[0:3],
        'techieads': models.TechieAd.objects.filter(deadline__gte=timezone.now()).filter(show__approved=True).order_by('deadline')[0:3],
        'societyapps': models.SocietyApplication.objects.filter(deadline__gte=timezone.now()).filter(society__approved=True).order_by('deadline')[0:2],
        'venueapps': models.VenueApplication.objects.filter(deadline__gte=timezone.now()).filter(venue__approved=True).order_by('deadline')[0:2],
        'showapps': models.ShowApplication.objects.filter(deadline__gte=timezone.now()).filter(show__approved=True).order_by('deadline')[0:3],
        'diary': util.diary_week(models.Performance.objects.filter(show__approved=True), today),
        'last_year': models.Show.objects.filter(end_date__gte=datetime.date(start_date.year - 1, start_date.month, start_date.day), start_date__lte=datetime.date(end_date.year - 1, end_date.month, end_date.day)).approved()[0:5],
        '2_years': models.Show.objects.filter(end_date__gte=datetime.date(start_date.year - 2, start_date.month, start_date.day), start_date__lte=datetime.date(end_date.year - 2, end_date.month, end_date.day)).approved()[0:5],
        '5_years': models.Show.objects.filter(end_date__gte=datetime.date(start_date.year - 5, start_date.month, start_date.day), start_date__lte=datetime.date(end_date.year - 5, end_date.month, end_date.day)).approved()[0:5],
        'weeks': weeks,
        'news': models.SocialPost.objects.all()[0:15],
    }
    return render(request, 'drama/index.html', context)


def diary(request, week=None):
    if week is None:
        week = timezone.now().date()
    else:
        week = datetime.datetime.strptime(week,"%Y-%m-%d").date()
    if 'end' in request.GET:
        end = datetime.datetime.strptime(request.GET['end'],"%Y-%m-%d").date()
    else:
        end = week + datetime.timedelta(days=56)
    prev = week - datetime.timedelta(days=7)
    events = models.Performance.objects.filter(show__approved=True)
    diary = util.diary(week, end, events, with_labels=True)
    current_term = models.TermDate.get_term(timezone.now())
    jump_form = forms.DiaryJumpForm(initial={'term':current_term.term, 'year':current_term.year})
    return render(request, "drama/diary.html", {'diary': diary, 'start':week, 'end':end, 'prev':prev, 'jump_form': jump_form})

def diary_week(request):
    if 'week' in request.GET:
        week = datetime.datetime.strptime(request.GET['week'],"%Y-%m-%d").date()
    else:
        raise Http404
    events = models.Performance.objects.filter(show__approved=True)
    term_label, week_label = models.TermDate.get_label(week)
    diary_week = {'html':util.diary_week(events, week, label=week_label), 'term_label':term_label}
    data = json.dumps(diary_week)
    return HttpResponse(data, content_type='application/json')

def diary_jump(request):
    form = forms.DiaryJumpForm(request.GET)
    if form.is_valid():
        term = get_object_or_404(models.TermDate,term=form.cleaned_data['term'], year=form.cleaned_data['year'])
        return redirect(reverse('diary', kwargs={'week': term.start.strftime('%Y-%m-%d')}))
    else:
        raise Http404

def auditions(request):
    aud_instances = models.AuditionInstance.objects.filter(end_datetime__gte=timezone.now()).order_by(
        'end_datetime', 'start_time').filter(audition__show__approved=True).select_related('audition')
    seen = set()
    seen_add = seen.add
    ads = [i.audition for i in aud_instances if i.audition.id not in seen and not seen_add(
        i.audition.id)]
    context = {'ads': ads, 'current_roletype': 'auditions',
               'current_pagetype': 'vacancies'}
    return render(request, 'drama/auditions.html', context)


def auditions_diary(request):
    return HttpResponse("Hello World")


def applications(request):
    showads = models.ShowApplication.objects.filter(
        deadline__gte=timezone.now()).filter(show__approved=True).order_by('deadline')
    socads = models.SocietyApplication.objects.filter(
        deadline__gte=timezone.now()).filter(society__approved=True).order_by('deadline')
    venueads = models.VenueApplication.objects.filter(
        deadline__gte=timezone.now()).filter(venue__approved=True).order_by('deadline')
    context = {'showads': showads, 'venueads': venueads, 'socads': socads,
               'current_roletype': 'applications', 'current_pagetype': 'vacancies'}
    return render(request, 'drama/applications.html', context)


def ad_role(request, show_slug, role_slug):
    role = get_object_or_404(
        models.TechieAdRole, slug=role_slug, ad__show__slug=show_slug)
    context = {'role': role, 'current_roletype': '',
               'current_pagetype': 'vacancies'}
    return render(request, 'drama/ad_role.html', context)


def techieads(request):
    ads = models.TechieAd.objects.filter(
        deadline__gte=timezone.now()).filter(show__approved=True).order_by('deadline')
    context = {'ads': ads, 'current_roletype': 'techie',
               'current_pagetype': 'vacancies'}
    return render(request, 'drama/techiead.html', context)


def autocomplete(request):
    sqs = SearchQuerySet().autocomplete(
        auto=request.GET.get('q', '')).load_all()[:10]
    suggestions = [{'name': result.object.name,
                   'string': result.object.dec_string,
                   'link': result.object.get_absolute_url(),
                   'type': result.object.class_name(),
                    } for result in sqs if result]
    data = json.dumps(suggestions)
    return HttpResponse(data, content_type='application/json')


def development(request):
    return HttpResponse("Hello World")


def contact_us(request):
    return HttpResponse("Hello World")


def techiead_item(request, slug, *args, **kwargs):
    return redirect(reverse('technical') + '#' + slug)

def audition_item(request, slug, *args, **kwargs):
    return redirect(reverse('auditions') + '#' + slug)

def application_item(request, slug, *args, **kwargs):
    return redirect(reverse('applications') + '#' + slug)


class MyCreateView(CreateView):
    model_name = None

    def get_context_data(self, **kwargs):
        context = super(MyCreateView, self).get_context_data(**kwargs)
        context['content_form'] = context['form']
        context['current_pagetype'] = self.model_name
        del context['form']
        return context

    @transaction.atomic()
    def form_valid(self, form):
        if self.model_name in ('shows',):
            self.success_url = '/'
            super(MyCreateView, self).form_valid(form)
            self.object.reslug()
            self.success_url = False
            result = redirect(self.get_success_url())
        else:
            result = super(MyCreateView, self).form_valid(form)

drama/templates/drama/about.html
{% extends "drama/base.html" %}

{% block title %}About Camdram{% endblock %}

{% block content %}
<div class="row">
  <div class="twelve columns">
    <h2>About Camdram</h2>
    
    <p>
      Camdram supports the student performing arts community in the 
      historic city of Cambridge, England.
    </p>
    
    <h3>How?</h3>
    
    <ul>
      <li>
        Our <a href="{% url 'diary' %}">event diary</a> makes it easy to see what’s happening 
        now, in the future, and for more than a decade past.
      </li>
      
      <li>
        You can easily <a href="{% url 'auditions' %}">get involved</a>, thanks to our listings of 
        auditions, production team vacancies, and society funding opportunities.
      </li>
      
      <li>
        We have information about the city's many <a href="{% url 'society-list' %}">societies</a> and 
        <a href="{% url 'venue-list' %}">performance spaces</a>.
      </li>
      
      <li>
        You can use our <a href="http://www.camdram.net/infobase" target="_blank">Infobase</a> to find and share useful information
        about putting on shows.
      </li>
    </ul>
    
    <p>Camdram has been 100% free since it began in 2004.  We're here for 
      students and staff - from either University and from other schools/colleges.
    </p>
    
    <p>
      All information comes from users like you, spanning drama, dance, comedy, 
      musicals, and music.  To use Camdram, your event doesn't have to be 
      <em>just</em> for students, so long as they're welcome.
    </p>
    
    <p>
      The site itself is maintained by volunteers in their spare time.  If you’re 
      interested in helping, 
      <a href="{% url 'contact-us' %}">contact us</a>.
    </p>
    
    <br />
  </div>
</div>
{% endblock %}

drama/templates/drama/application_form.html
{% extends "drama/base.html" %}

{% block title %}{% if object %}Edit{% else %}Add{% endif %} Application{% endblock %}

{% block content %}
<div class="row">
  {% if object %}
  <h3>Edit Application</h3>
  {% else %}
  <h3>Add Application</h3>
  {% endif %}
  <div class="panel">
    <p>Use the form below modify your application advertisement.</p>
  </div>
  <form action="" method="post">
  {% csrf_token %}
  {% include "drama/application_subform.html" with form=content_form %}
  <div class="text-right">
  <button type="submit">Save</button>
  </div>
  </form>
</div>
{% endblock %}

drama/templates/drama/application_formset.html
{% extends "drama/base.html" %}
{% load drama_admin %}
{% block title %}Edit Application{% endblock %}

{% block content %}
{% admin_panel parent %}
<div class="row">
  {% if object %}
  <h3>Edit Applications</h3>
  {% else %}
  <h3>Add Applications</h3>
  {% endif %}
  <div class="panel">
    <p>Use the form below modify your application advertisements.</p>
  </div>
  <div class="large-12 columns">
    <form action="" method="post">
      {{ content_form.management_form }}
      <div id="applications" class="{{prefix}}application_set collection">
  {% csrf_token %}
  {% for form in content_form %}
  <div class="row" id="{{form.DELETE.id_for_label}}">
    {{form.application_ptr}}
  {% include "drama/application_subform.html" %}
  <hr />
  </div>
  {% endfor %}
  </div>
  <div id="empty_form" style="display:none">
    <div class="row" id="{{content_form.empty_form.DELETE.id_for_label}}">
    {% include "drama/application_subform.html" with form=content_form.empty_form %}
    <hr />
    </div>
  </div>
  <ul class="inline-list audition-links">
    <li> <a href="#" id="{{prefix}}application_set" class="add_more">Add application</a></li>
  </ul>
  <div class="text-right">
  <button type="submit">Save</button>
  </div>
  </form>
  </div>
</div>
{% endblock %}

drama/templates/drama/audition_confirm_delete.html
confirm_delete.html

drama/templates/drama/audition_form_item.html
	<div class="audition" id="{{form.DELETE.id_for_label}}">
	  {{form.id}}
	  <div class="row">
	    <div class="large-1 column">
	      <label class="{{form.date.css_classes}} right inline" for="{{form.date.id_for_label}}">
		Date
	      </label>
	    </div>
	    <div class="{{form.date.css_classes}} large-2 columns">
	      {{form.date}}
	      {% for error in form.date.errors %}
	      <small class="error">{{error}}</small>
	      {% endfor %}
	    </div>
	    <div class="large-2 column">
	      <label class="{{form.start_time.css_classes}} right inline" for="{{form.end_date.id_for_label}}">
		Start time
	      </label>
	    </div>
	    <div class="{{form.start_time.css_classes}} large-2 columns">
	      {{form.start_time}}
	      {% for error in form.start_time.errors %}
	      <small class="error">{{error}}</small>
	      {% endfor %}
	    </div>
	    <div class="large-2 column">
	      <label class="{{form.end_time.css_classes}} right inline" for="{{form.end_time.id_for_label}}">
		End time
	      </label>
	    </div>
	    <div class="{{form.end_time.css_classes}} large-2 columns">
	      {{form.end_time}}
	      {% for error in form.end_time.errors %}
	      <small class="error">{{error}}</small>
	      {% endfor %}
	    </div>
	    <div class="large-1 columns right">
	      <div class="hide">
		{{form.DELETE}}
	      </div>
	      <a href="#" id="{{form.DELETE.id_for_label}}" class="delete-link"><i class="fa fa-trash-o"></i></a>
	    </div>
	  </div>
	  <div class="row">
	    <div class="large-3 columns">
	      <label class="{{form.location.css_classes}} right inline" for="{{form.location.id_for_label}}"> {{form.location.label}} </label>
	    </div>
	    <div class="{{form.location.css_classes}} large-9 columns">
	      {{form.location}}
	      {% for error in form.location.errors %}
	      <small class="error">{{error}}</small>
	      {% endfor %}
	    </div>
	  </div>
	</div>

drama/templates/drama/base.html
{% load staticfiles %}
{% load drama_admin %}
{% load pipeline %}
<!DOCTYPE html>
<html>
  <head>
    <link rel='icon' href='/static/favicon.png' type='image/png' />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/humanity/jquery-ui.css" />
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="//cdnjs.cloudflare.com/ajax/libs/foundation/5.5.0/js/foundation.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/foundation/5.5.0/js/vendor/modernizr.js"></script>
    {% javascript 'vendor' %}
    {% javascript 'app' %}
    {% stylesheet 'app' %}
    {% stylesheet 'vendor' %}
    <title>{% block title %}{% endblock %} - Camdram</title>
    {% block extra_headers %}{% endblock %}
  </head>
  
  <body>
    <div id="wrapper"> 
      <nav id="header-bar">
	<section>
	  <ul class="left hide-for-small">
            <li><a href="{% url 'about' %}">
		About</a>
	    </li>
	    <li><a href="{% url 'development' %}">
		Development</a>
	    </li>
	    <li><a href="{% url 'contact-us' %}">
		Contact Us</a>
	    </li>
	  </ul>
	  
	  <ul class="right">
	    {% if user.is_authenticated %}
	    <li id="account-link">
	      <a href="#" data-dropdown="account-dropdown" data-options="is_hover:true">{% if user.get_full_name %}{{user.get_full_name}}{% elif user.email %}{{user.email}}{% else %}{{user.username}}{% endif %}</a>
	      <ul id="account-dropdown" class="topbar-dropdown" data-dropdown-content="" data-options="align_right">
		<li><a href="{% url 'password_change' %}"><i class="fa fa-cogs fa-fw"></i> Account Settings</a></li>
		<li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> Log out</a></li>
        </ul>
    </li>
	    {% else %}
	    <li><a href="{% url 'registration_register' %}">Create an account</a></li>
	    <li id="login-link"><a href="{% url 'login' %}">Log in</a></li>
	    {% endif %}
	  </ul>
	</section>
      </nav>
      <header>
	<div class="row">
	 <div class="large-3 columns logo">
	   <h1><a href="{% url 'home' %}"><img src="{% static 'images/logo.png' %}" alt="camdram" title="camdram"/></a></h1>
	 </div>
	 <div class="large-9 columns search">
	  <form method="get" action="/search" class="searchform" id="search_form">
	    <i class="fa fa-search"></i>
	    {% if form.q %}{{form.q}}{% else %}{{search_form.q}}{% endif %}
	    <div class="results">
	      <ul></ul>
	      <div class="noresults">No results found for &quot;<span class="query"></span>&quot;</div>
              <div class="fulltext"><a href="#">...perform a search for &quot;<span class="query"></span>&quot;</a></div>
	    </div>
            <i class="fa fa-spinner fa-spin"></i>
	  </form>
	 </div>
	</div>
      </header>
      <nav class="top-bar" data-topbar role="navigation">
	<section class="top-bar-section">
	  <ul class="left">
	    {% for id,item in navitems_default %}
	    <li{% if id == current_pagetype %} class="active"{% endif %}>
	      <a href="{{item.path}}">{{item.text}}</a>
	    </li>
	    {% endfor %}
	  </ul>
	  <ul class="right">
	    <li class="has-dropdown">
              <a href="#" id="nav-edit-link" ><i class="fa fa-edit"></i></a>
              <ul id="edit-menu" class="dropdown">
		{% block extra_menu %}{% endblock %}
		{% default_menu %}
	      </ul>
	    </li>
	  </ul>
	</section>
      </nav>
      <section id="content">
	{% block content %}{% endblock %}
      </section>
    </div>
    <footer>
      <div id="sitemap" class="row">
        <div class="large-4 columns">
          <h5>Site Map</h5>
	  {% for id,item in navitems_default %}
	  <a href="{{item.path}}">{{item.text}}</a><br />
	  {% endfor %}
	</div>
	<div class="large-4 columns">
            <h5>Vacant Positions</h5>
            <a href="{% url 'technical' %}">Technical</a><br/>
            <a href="{% url 'auditions' %}">Actors</a><br/>
            <a href="{% url 'applications' %}">Directors/Producers</a><br/>
        </div>
        <div class="large-4 columns">
          <h5>About</h5>
          <a href="{% url 'about' %}">About Camdram</a><br/>
          <a href="{% url 'development' %}">Development</a><br/>
          <a href="{% url 'privacy' %}">Privacy policy</a><br/>
          <a href="{% url 'contact-us' %}">Contact Us</a><br/>
        </div>
      </div>
      
      <div id="copyright" class="row">
        <p>&copy; Association of Cambridge Theatre Societies and contributing groups 2004 &#8212; 2014.
          Comments &amp; queries to <a href="mailto:websupport@camdram.net">websupport@camdram.net</a>
        </p>
      </div>
    </footer>
<script> $(document).foundation(); </script>
  </body>
</html>

drama/templates/drama/default_menu.html
{% if approval_queue %}
<li><a href="{% url 'approvals' %}"><i class="fa fa-check-circle fa-fw"></i> Approval Queue</a></li>
{% endif %}
{% if view_issues %}
<li><a href="{% url 'issues:list' %}"><i class="fa fa-warning fa-fw"></i> Issues</a></li>
{% endif %}
{% if admin %}
<li><a href="{% url 'admin:index'%}"><i class="fa fa-key fa-fw"></i> Admin Interface</a></li>
{% endif %}
{% if view_emaillists %}
<li><a href="{% url 'emaillist-list' %}"><i class="fa fa-envelope"></i> Mailing Lists</a></li>
{% endif %}
{% if add_show %}
<li><a href="{% url 'show-admin'%}"><i class="fa fa-ticket fa-fw"></i> Show Admin</a></li>
<li><a href="{% url 'show-new' %}"><i class="fa fa-plus-circle fa-fw"></i> Add a show</a></li>
{% endif %}
{% if add_venue %}
<li><a href="{% url 'venue-new' %}"><i class="fa fa-plus-circle fa-fw"></i> Add a venue</a></li>
{% endif %}
{% if add_society %}
<li><a href="{% url 'society-new' %}"><i class="fa fa-plus-circle fa-fw"></i> Add a society</a></li>
{% endif %}
{% if add_role %}
<li><a href="{% url 'role-new' %}"><i class="fa fa-plus-circle fa-fw"></i> Add a role</a></li>
{% endif %}

drama/templates/drama/emaillist_confirm_delete.html
confirm_delete.html

drama/templates/drama/person_confirm_delete.html
confirm_delete.html

drama/templates/drama/society.html
{% extends "drama/base.html" %}
{% block title %}Society: {{society.name}}{% endblock %}

{% block content %}
<div class="row">
  <div class="large-12 columns panel">
    <h2>{{society.name}}<small> - {{society.shortname}}</small></h2>
    <p>{{society.desc|safe}}</p>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    {% with title="Get involved with "|add:society.name|add:" shows:" %}
    {% include "drama/vacancies-panel.html" with title=title ourapps=societyapps%}
    {% endwith %}
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <h3>Shows</h3>
    {% include "drama/diary.html" with events=shows %}
  </div>
</div>
{% endblock %}

drama/templates/drama/society_list.html
{% extends "drama/base.html" %}
{% block title %}Societies{% endblock %}

{% block content %}
<div class="row">
  <div class="large-12 columns">
    <h3>Societies</h3>
  </div>
</div>

<ul class="large-block-grid-2" id="societies_list">
{% for society in object_list %}
<li id="{{society.slug}}">
  <div class="row">
    <div class="large-12 columns">
      <h5>{{society.get_link}}{% if society.shortname %}<small> - {{society.shortname}}</small>{% endif %}</h5>
      <p>{{society.desc|truncatechars:200}}<br />
	[<a href="{{society.get_absolute_url}}">Read More</a>]
      </p>
    </div>
  </div>
</li>
{% endfor %}
</ul>
{% endblock %}